UscProject/Areas/Admin/ViewModels/ShowKarjoInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using UscProject.Models;

namespace UscProject.Areas.Admin.ViewModels
{
    public class ShowKarjoInformation
    {
        public string UserName;
        public string Email;
        public string ImageName;
        public List<TheFormsOFEachResumeFinal_Result> theForms;
        public bool PicStatus;
    }
}

UscProject/Areas/Admin/Controllers/KarJoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Areas.Admin.ViewModels;
using UscProject.Models;

namespace UscProject.Areas.Admin.Controllers
{
    public class KarJoController : Controller
    {
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        // GET: Admin/KarJo

        public ActionResult KarjoTables()
        {
            List<KarjoInformation> karjos = new List<KarjoInformation>();
            var karjo = db.EmployerTB.ToList();
            foreach (var item in karjo)
            {
                var temp = new KarjoInformation();
                int? id = db.EmployerTB.Where(p => p.EmployerID == item.EmployerID).First().ResumeID;
                temp.UserName = db.UserTB.Where(p => p.UserID == item.UserID).First().UserName;
                temp.Email = db.UserTB.Where(p => p.UserID == item.UserID).First().Email;
                int userid = db.EmployerTB.Where(p => p.EmployerID == item.EmployerID).First().UserID;
                temp.dateofregister = db.UserTB.Where(p => p.UserID == userid).First().RegesterDate;
                temp.id = id;
                karjos.Add(temp);
            }
            return View(karjos);
        }
        public ActionResult ShowKarjoInformation(int id)
        {
            var model = new ShowKarjoInformation();
            model.theForms = db.TheFormsOFEachResumeFinal(id).ToList();
            int userid = db.EmployerTB.Where(p => p.ResumeID == id).FirstOrDefault().UserID;
            var user = db.UserTB.Find(userid);
            model.Email = user.Email;
            model.UserName = user.UserName;
            if (user.ImageName)
            {
                model.ImageName = user.PictureName;
                model.PicStatus = true;
            }
            else
            {
                model.ImageName = null;
                model.PicStatus = false;
            }
            return View(model);
        }
        public ActionResult ShowFormsDetails(int id)
        {
            var forms = db.FormTB.Find(id);
            return PartialView(forms);
        }

    }
}

UscProject/Areas/KarJo/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Areas.KarJo.ViewModel;
using UscProject.Models;

namespace UscProject.Areas.KarJo.Controllers
{
    public class FormController : Controller
    {
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        // GET: KarJo/Form
        public ActionResult FormTables()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = user.UserID;
            var employer = db.EmployerTB.Where(e => e.UserID == userid).First();
            int employerid = employer.EmployerID;
            int? resumid = db.EmployerTB.Where(e => e.UserID == user.UserID).First().ResumeID;
            var count = db.TheFormsOFEachResume(resumid).ToList();

            List<FormTable> form = new List<FormTable>();
            int i = 1;
            foreach (var item in count)
            {
                var f = new FormTable();
                f.formid = item.FormID;
                f.count = i++;
                f.DateOfMake = item.RequestDtae;
                form.Add(f);
            }
            return View(form);
        }
        public ActionResult ShowFormsDetails(int id)
        {
            var form = db.FormTB.Find(id);
            return PartialView(form);
        }
        public void DeleteForm(int id)
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = user.UserID;
            var employer = db.EmployerTB.Where(e => e.UserID == userid).First();
            int employerid = employer.EmployerID;
            int? resumid = db.EmployerTB.Where(e => e.UserID == user.UserID).First().ResumeID;
            var resmeemployee = db.ResumeEmployeeTB.Where(p => p.FormID == id && p.ResumeID == resumid).First();
            db.ResumeEmployeeTB.Remove(resmeemployee);
            db.SaveChanges();
        }
    }
}

UscProject/Areas/KarJo/Controllers/PanelController.cs
using DocumentFormat.OpenXml.Vml.Office;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Areas.KarJo.ViewModel;
using UscProject.Models;

namespace UscProject.Areas.KarJo.Controllers
{
    public class PanelController : Controller
    {
        // GET: KarJo/Panel

        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        public ActionResult Header()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u=>u.UserName==username).SingleOrDefault();
            return PartialView(model);
        }
        public ActionResult Index()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = model.UserID;
            int emloyerid = db.EmployerTB.Where(e => e.UserID == userid).First().EmployerID;
            int? resumeid = db.EmployerTB.Find(emloyerid).ResumeID;
            var sentforms = db.TheFormsOFEachResume(resumeid).Count();
            ViewBag.sentforms = sentforms;
            ViewBag.resume = resumeid;
            return View(model);
        }
        public ActionResult PersonalInformation()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult PersonalInformation(UserTB user, HttpPostedFileBase ImgUp)
        {
            if (ImgUp != null)
            {
                user.ImageName = true;
                if (user.PictureName != "image.png")
                {
                    System.IO.File.Delete(Server.MapPath("/Files/UserPictures/Custom/KarJo/" + user.PictureName));
                }

                user.PictureName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
                ImgUp.SaveAs(Server.MapPath("/Files/UserPictures/Custom/KarJo/" + user.PictureName));


            }
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return View(user);
        }
        public class JsonData
        {
            public bool Status { get; set; }
            public string Message { get; set; }

        }
    }
}

UscProject/Areas/KarJo/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Models;

namespace UscProject.Areas.KarJo.Controllers
{
    public class ResumeController : Controller
    {
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        // GET: KarJo/Resume
        public ActionResult EditResume()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = user.UserID;
            var employer = db.EmployerTB.Where(o => o.UserID == userid).First();
            var resume = db.ResumeTB.Where(e => e.ResumeID == employer.ResumeID).First();
            if (user.ImageName == false)
            {
                ViewBag.path = Url.Content("/Files/UserPictures/Default/UserProfile.jpg");
            }
            else
            {
                ViewBag.path = Url.Content("/Files/UserPictures/Custom/KarJo" + user.PictureName);
            }
            return View(resume);
        }
        [HttpPost]
        public JsonResult EditResume(ResumeTB resume)
        {
            db.Entry(resume).State = EntityState.Modified;

            db.SaveChanges();
            return Json(new JsonData()
            {
                Status = true
            });
        }
        public ActionResult NewResume()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = user.UserID;
            var emloyer = db.EmployerTB.Where(e => e.UserID == userid).First();
            if (emloyer.ResumeID == null)
            {
                return View();
            }
            else
            {
                var resume = db.ResumeTB.Find(emloyer.ResumeID);
                return RedirectToAction("EditResume");
            }

        }
        [HttpPost]
        public JsonResult NewResume(ResumeTB resume)
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = user.UserID;
            var employer = db.EmployerTB.Where(e => e.UserID == userid).First();
            resume.RequestDate = DateTime.Today;
            db.Entry(resume).State = EntityState.Added;
            employer.ResumeID = resume.ResumeID;
            db.SaveChanges();
            return Json(new JsonData()
            {
                Status = true
            });
        }
        public class JsonData
        {
            public bool Status { get; set; }
            public string Message { get; set; }

        }
    }
}

UscProject/Areas/Admin/Views/KarJo/KarjoTables.cshtml
@model IEnumerable< UscProject.Areas.Admin.ViewModels.KarjoInformation>
@{
    ViewBag.Title = "KarjoTables";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<div class="row justify-content-between align-items-center mb-10">

    <!-- Page Heading Start -->
    <div class="col-12 col-lg-auto mb-20">
        <div class="page-heading">
            <h3 class="title">جداول <span>/ تصویر زمینه</span></h3>
        </div>
    </div><!-- Page Heading End -->

</div><!-- Page Headings End -->

<div class="row">

    <!--Basic Start-->
    <div class="col-12 mb-30">
        <div class="box">
            <div class="box-head">
                <h3 class="title">پایه</h3>
            </div>
            <div class="box-body">

                <table class="table footable" data-paging="true" data-filtering="true" data-sorting="true" data-breakpoints='{ "xs": 480, "sm": 768, "md": 992, "lg": 1200, "xl": 1400 }'>
                    <thead>
                        <tr>
                            <th data-name="نام">نام</th>
                            <th data-name="نام">ایمیل</th>
                            <th data-name="نام">تاریخ ثبت نام</th>
                            <th data-name="نام">عملیات</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var g in Model)
                        {
                        <tr>
                            <td>@g.UserName</td>
                            <td>@g.Email</td>
                            <td>@g.dateofregister</td>
                            @if (g.id == null)
                            {
                                <td>رزومه ای ندارد</td>
                            }
                            else
                            {
                             <td><a href="@Url.Action("ShowKarjoInformation","KarJo", new { id = g.id})"><span class="badge badge-pill badge-success">مشاهده پروفایل</span></a></td>
                            }
                        </tr>

                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    </div>
    <!--Basic End-->
    @section PageScript
{
        <script src="~/Areas/Admin/Content/assets/js/plugins/moment/moment.min.js"></script>
        <script src="~/Areas/Admin/Content/assets/js/plugins/footable/footable.min.js"></script>
        <script src="~/Areas/Admin/Content/assets/js/plugins/footable/footable.active.js"></script>
    }

UscProject/Areas/Admin/Views/KarJo/ShowFormsDetails.cshtml
@model UscProject.Models.FormTB
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>مشخصات بسته های اگهی</title>
    <style>

        #t1 {
            border: 1px solid white;
            border-collapse: collapse;
            text-align: center;
        }

            #t1 th {
                border: 1px solid white;
                border-collapse: collapse;
                text-align: center;
            }

            #t1 td {
                border: 1px solid white;
                border-collapse: collapse;
                text-align: center;
                padding: 5px;
            }
    </style>
</head>
<body>
    <h4>بسته اگهی</h4>

    <table id="t1" style="width:100%">
        <tr>
            <th>شهذ</th>
            <td>@Model.City</td>
        </tr>
        <tr>
            <th>منطقه</th>
            <td>@Model.Region</td>
        </tr>

        <tr>
            <th>مزایای شغلی</th>
            <td>@Model.Benefits</td>
        </tr>

        <tr>
            <th>تعداد روز ها</th>
            <td>@Model.WorkingDays</td>
        </tr>

        <tr>
            <th>توضیحات</th>
            <td>@Model.FormText</td>
        </tr>
        <tr>
            <th>توضیحات تکمیلی</th>
            <td>@Model.JobDescRiption</td>
        </tr>
    </table>

</body>
</html>

UscProject/Areas/Admin/Views/KarJo/ShowKarjoInformation.cshtml
@model UscProject.Areas.Admin.ViewModels.ShowKarjoInformation
@{
    ViewBag.Title = "ShowKarjoInformation";
    ViewBag.UserProfile = "active";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";

    string path = Url.Content("~/Files/UserPictures/Default/DefaultPic.png");
    if (Model.PicStatus)
    {
        path = Url.Content("~/Files/UserPictures/Custom/KarJo/" +Model.ImageName);

    }
    else
    {
        path = Url.Content("~/Files/UserPictures/Default/UserProfile.jpg");
    }
}



<h3 class=" mb-35">کارجو</h3>
<div class="row  mb-50">

    <div class="pricing-two col-lg-4 col-12 mb-30">
        <div class="inner">

            <div class="body">
                <img src="@path" class="rounded mx-auto d-block" alt="...">
                <br />
                    <h5 class="title">@Model.UserName</h5>
                <ul>

                    <li>@Model.Email</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-lg-8 col-12 mb-30">
        <div class="box">
        </div>
    </div>

</div>
<div class="col-12 mb-30">
    <div class="box">
        <div class="box-head">
            <h3 class="title">جدول فرم ها</h3>
        </div>
        <div class="box-body">

            <table class="table table-bordered data-table data-table-export">
                <thead>
                    <tr>
                        <th>شرکت</th>
                        <th>منطقه</th>
                        <th>شهر</th>
                        <th>تاریخ ارسال</th>
                        <th>وضعیت</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var g in Model.theForms)
                    {
                    <tr>
                        <td>@g.CompanyName</td>
                        <td>@g.Region</td>
                        <td>@g.City</td>
                        <td>@g.DateOfSend</td>
                        <td class="col-lg-3 col-md-4 col-sm-6 col-12">
                            <a onclick="view(@g.FormID)" data-clipboard-text="fa fa-user-circle-o"><i class="fa fa-user-circle-o" aria-hidden="true"></i> </a>
                        </td>
                    </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>منطقه</th>
                        <th>شهر</th>
                        <th>تاریخ فرم</th>
                        <th>جعبه</th>
                        <th>وضعیت</th>
                    </tr>
                </tfoot>
            </table>

        </div>
    </div>
</div>
<div class="modal fade" id="MyModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body" id="myModalBody">
                ...
            </div>
        </div>
    </div>
</div>
<!-- Pricing Four Start -->
@section PageScript
{

    <script src="~/Areas/Admin/Content/assets/js/plugins/datatables/datatables.min.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/datatables/datatables.active.js"></script>
    <script>
        function view(id) {
            $.get("/Admin/KarJo/ShowFormsDetails/" + id, function (res) {

                $("#MyModal").modal();
                $("#myModalBody").html(res);

            });
        }
    </script>
}