UscProject/Areas/Admin/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Models;
using Newtonsoft.Json;
using UscProject.Areas.Admin.ViewModels;
using System.Data.Entity.Core.Objects;
using Microsoft.Ajax.Utilities;
using System.Data.Entity;
using System.IO;
using UscProject.Help;
using System.Net.Mail;
using System.Net;
using IdentityServer4.Models;
using DocumentFormat.OpenXml.Vml.Office;
using System.Web.Security;

namespace UscProject.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        // GET: Admin/Panel
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();

        public ActionResult Header()
        {
            var user = db.UserTB.Find(1);
            return PartialView(user);
        }

        public ActionResult Index()
        {
            ViewBag.resume = db.ResumeTB.Count();
            ViewBag.forms = db.FormTB.Count();
            ViewBag.karjo = db.EmployeeTB.Count();
            ViewBag.karfarma = db.EmployerTB.Count();

            List<DataPoint> dataPoints1 = new List<DataPoint>();
            List<DataPoint> dataPoints2 = new List<DataPoint>();
            List<DataPoint> dataPoints3 = new List<DataPoint>();
            for (int i = DateTime.Now.Year; i >= 2018; i--)
            {
                var Gold = db.OrderDetailTB.Where(p => p.BuyDate.Value.Year == i && p.BoxCategoryID == 1).Sum(p => (int?)p.UnitPrice) ?? 0;
                var Silver = db.OrderDetailTB.Where(p => p.BuyDate.Value.Year == i && p.BoxCategoryID == 2).Sum(p => (int?)p.UnitPrice) ?? 0;
                var noghre = db.OrderDetailTB.Where(p => p.BuyDate.Value.Year == i && p.BoxCategoryID == 3).Sum(p => (int?)p.UnitPrice) ?? 0;

                DataPoint data1 = new DataPoint(i.ToString(), Convert.ToDouble(Gold));
                dataPoints1.Add(data1);


                DataPoint data2 = new DataPoint(i.ToString(), Convert.ToDouble(Silver));
                dataPoints2.Add(data2);


                DataPoint data3 = new DataPoint(i.ToString(), Convert.ToDouble(noghre));
                dataPoints3.Add(data3);

            }

            ViewBag.DataPoints1 = JsonConvert.SerializeObject(dataPoints1);
            ViewBag.DataPoints2 = JsonConvert.SerializeObject(dataPoints2);
            ViewBag.DataPoints3 = JsonConvert.SerializeObject(dataPoints3);
            var model = db.BoxCategory.ToList();
            return View(model);
        }


        public ActionResult PersonalInformation()
        {

            var model = db.UserTB.Find(1);
            if (model.ImageName)
            {
                ViewBag.PicStatus = true;
            }
            else
            {
                ViewBag.PicStatus = false;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult PersonalInformation(UserTB user, HttpPostedFileBase ImgUp)
        {
            if (ImgUp != null)
            {
                user.ImageName = true;
                if (user.PictureName != "image.png")
                {
                    System.IO.File.Delete(Server.MapPath("/Files/UserPictures/Custom/" + user.PictureName));
                }

                user.PictureName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
                ImgUp.SaveAs(Server.MapPath("/Files/UserPictures/Custom/" + user.PictureName));


            }

            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return View(user);
        }


        [Route("LogOut")]
        public class JsonData
        {
            public bool Status { get; set; }
            public string Message { get; set; }

        }
    }
}

UscProject/Areas/KarFarma/Controllers/PanelController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Vml.Office;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using UscProject.Areas.KarFarma.ViewModel;
using UscProject.Models;

namespace UscProject.Areas.KarFarma.Controllers
{
    [Authorize(Roles = "Karfarma")]
    public class PanelController : Controller
    {
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        // GET: KarFarma/Panel
        public ActionResult Index()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(p => p.UserName == username).FirstOrDefault();
            int employeeid = db.EmployeeTB.Where(p => p.UserID == user.UserID).FirstOrDefault().EmployeeID;
            ViewBag.CompanyName = db.EmployeeTB.Where(o => o.EmployeeID == employeeid).First().CompanyName;
            int userid = db.EmployeeTB.Where(o => o.EmployeeID == employeeid).First().UserID;
            var model = db.UserTB.Find(userid);
            ViewBag.Email = db.UserTB.Where(o => o.UserID == userid).First().Email;
            ViewBag.ResumeSent = db.TheResumeForEmployees(employeeid).Count();
            ViewBag.Forms = db.TheTotallFormsOfKarfarma(employeeid).Count();
            return View(model);
        }
        public ActionResult Header()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(t => t.UserName == username).FirstOrDefault();
            var model = db.UserTB.Where(o => o.UserID == user.UserID).First();
            return PartialView(model);

        }
        [HttpGet]
        public ActionResult PersonalInformation()
        {
            var username = User.Identity.Name;
            var user = db.UserTB.Where(p => p.UserName == username).FirstOrDefault();
            var model = db.UserTB.Where(o => o.UserID == user.UserID).First();
            ViewBag.CompanyName = db.EmployeeTB.Where(p => p.UserID == user.UserID).First().CompanyName;
            return View(model);
        }

        [HttpPost]
        public ActionResult PersonalInformation(UserTB user, string companyname, HttpPostedFileBase ImgUp)
        {
            //var picStatus = user.ImageName;
            //if (picStatus == false)
            //{
            //    ImgUp = null;
            //}
            //else 
            //{
            //    user.PictureName=
            //}

            if (ImgUp != null)
            {
                user.ImageName = true;
                if (user.PictureName != "image.png")
                {
                    System.IO.File.Delete(Server.MapPath("/Files/UserPictures/Custom/Karfarma/" + user.PictureName));
                }

                user.PictureName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
                ImgUp.SaveAs(Server.MapPath("/Files/UserPictures/Custom/Karfarma/" + user.PictureName));


            }
            var employee = db.EmployeeTB.Where(p => p.UserID == user.UserID).First();
            employee.CompanyName = companyname;
            db.Entry(employee).State = EntityState.Modified;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            ViewBag.CompanyName = companyname;
            return View(user);
        }

        public class JsonData
        {
            public bool Status { get; set; }
            public string Message { get; set; }

        }
    }
}

UscProject/Areas/KarJo/Controllers/PanelController.cs
using DocumentFormat.OpenXml.Vml.Office;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Areas.KarJo.ViewModel;
using UscProject.Models;

namespace UscProject.Areas.KarJo.Controllers
{
    public class PanelController : Controller
    {
        // GET: KarJo/Panel

        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();
        public ActionResult Header()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u=>u.UserName==username).SingleOrDefault();
            return PartialView(model);
        }
        public ActionResult Index()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            int userid = model.UserID;
            int emloyerid = db.EmployerTB.Where(e => e.UserID == userid).First().EmployerID;
            int? resumeid = db.EmployerTB.Find(emloyerid).ResumeID;
            var sentforms = db.TheFormsOFEachResume(resumeid).Count();
            ViewBag.sentforms = sentforms;
            ViewBag.resume = resumeid;
            return View(model);
        }
        public ActionResult PersonalInformation()
        {
            var username = User.Identity.Name;
            var model = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult PersonalInformation(UserTB user, HttpPostedFileBase ImgUp)
        {
            if (ImgUp != null)
            {
                user.ImageName = true;
                if (user.PictureName != "image.png")
                {
                    System.IO.File.Delete(Server.MapPath("/Files/UserPictures/Custom/KarJo/" + user.PictureName));
                }

                user.PictureName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
                ImgUp.SaveAs(Server.MapPath("/Files/UserPictures/Custom/KarJo/" + user.PictureName));


            }
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return View(user);
        }
        public class JsonData
        {
            public bool Status { get; set; }
            public string Message { get; set; }

        }
    }
}

UscProject/Controllers/BoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UscProject.Models;

namespace UscProject.Controllers
{
    public class BoxController : Controller
    {
        // GET: Box
        OnlineProjectUSCEntities db = new OnlineProjectUSCEntities();


        [Route("Boxes")]
        public ActionResult Index()
        {
            var box = db.BoxCategory.ToList();
            //....چک کنیم چه کسی لاگین هست
            if (User.Identity.IsAuthenticated)
            {

                var username = User.Identity.Name;
                var user = db.UserTB.Where(u => u.UserName == username).SingleOrDefault();
                int RoleId = user.RoleID;
                if (RoleId == 1)
                {
                    ViewBag.status = false;
                    ViewBag.message = "شما ادمین هستید!";
                }
                else if (RoleId == 2)
                {
                    //...وضعیت اخرین بسته را باید چک کنیم
                    int employeeid = db.EmployeeTB.Where(u => u.UserID == user.UserID).SingleOrDefault().EmployeeID;
                    var the_last_order = db.OrderDetailTB.Where(p => p.EmployeeID == employeeid).OrderByDescending(u => u.BuyDate).First();
                    var final_date_permission = the_last_order.BuyDate.Value.AddDays(the_last_order.BoxCategory.DatePermission);
                    var the_totall_forms_of_last_order = db.TheTotallFormsAfterTheLastOrderForEmployee_finallversion(employeeid, DateTime.Today).Count();
                    var the_totall_forms_permission = the_last_order.BoxCategory.CountPermisson;
                    if (final_date_permission < DateTime.Today)
                    {
                        if (the_totall_forms_of_last_order < the_totall_forms_permission)
                        {
                            ViewBag.status = false;
                            ViewBag.message = "شما هنوز بسته قبلی را میتوانید استفاده کنید!";
                        }
                        else
                        {
                            ViewBag.status = true;
                            ViewBag.message = "خرید کنید";
                        }

                    }
                    else
                    {
                        ViewBag.status = true;
                        ViewBag.message = "خرید کنید";
                    }
                }
                else if (RoleId == 3)
                {
                    ViewBag.status = false;
                    ViewBag.message = "شما کارجو هستید و دسترسی ندارید";
                }
            }
            else 
            {
                ViewBag.status = false;
                ViewBag.message = "به حساب کاربری خود وارد شوید!";
            }
            return View(box);
        }
       
    }
}

UscProject/Areas/Admin/Views/Panel/Index.cshtml
@model IEnumerable<UscProject.Models.BoxCategory>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}



<!-- Page Headings Start -->
<div class="row justify-content-between align-items-center mb-10">

    <!-- Page Heading Start -->
    <div class="col-12 col-lg-auto mb-20">
        <div class="page-heading">
            <h3>داشبورد <span>/ تجارت الکترونیکی</span></h3>
        </div>
    </div><!-- Page Heading End -->
    <!-- Page Button Group Start -->
    <div class="col-12 col-lg-auto mb-20">
        <div class="page-date-range">
            <input type="text" class="form-control input-date-predefined">
        </div>
    </div><!-- Page Button Group End -->

</div><!-- Page Headings End -->
<!-- Top Report Wrap Start -->
<div class="row">
    <!-- Top Report Start -->
    <div class="col-xlg-3 col-md-6 col-12 mb-30">
        <div class="top-report">

            <!-- Head -->
            <div class="head">
                <h4>مجموع رزومه های </h4>
                <a href="#" class="view"><i class="zmdi zmdi-eye"></i></a>
            </div>

            <!-- Content -->
            <div class="content">
                <h2>@ViewBag.resume</h2>
            </div>

            <!-- Footer -->
            <div class="footer">
                <div class="progess">
                    <div class="progess-bar" style="width: @ViewBag.resume;"></div>
                </div>
            </div>

        </div>
    </div><!-- Top Report End -->
    <!-- Top Report Start -->
    <div class="col-xlg-3 col-md-6 col-12 mb-30">
        <div class="top-report">

            <!-- Head -->
            <div class="head">
                <h4>تعداد کل فرم های ارسالی</h4>
                <a href="#" class="view"><i class="zmdi zmdi-eye"></i></a>
            </div>

            <!-- Content -->
            <div class="content">
                <h2>@ViewBag.forms</h2>
            </div>

            <!-- Footer -->
            <div class="footer">
                <div class="progess">
                    <div class="progess-bar" style="width: @ViewBag.forms;"></div>
                </div>
            </div>

        </div>
    </div><!-- Top Report End -->
    <div class="col-xlg-3 col-md-6 col-12 mb-30">
        <div class="top-report">

            <!-- Head -->
            <div class="head">
                <h4>تعداد کل کارجو</h4>
                <a href="#" class="view"><i class="zmdi zmdi-eye"></i></a>
            </div>

            <!-- Content -->
            <div class="content">
                <h2>@ViewBag.karjo</h2>
            </div>

            <!-- Footer -->
            <div class="footer">
                <div class="progess">
                    <div class="progess-bar" style="width: @ViewBag.karjo;"></div>
                </div>
            </div>

        </div>
    </div><!-- Top Report End -->
    <div class="col-xlg-3 col-md-6 col-12 mb-30">
        <div class="top-report">

            <!-- Head -->
            <div class="head">
                <h4>تعداد کل کارفرما</h4>
                <a href="#" class="view"><i class="zmdi zmdi-eye"></i></a>
            </div>

            <!-- Content -->
            <div class="content">
                <h2>@ViewBag.karfarma</h2>
            </div>

            <!-- Footer -->
            <div class="footer">
                <div class="progess">
                    <div class="progess-bar" style="width: @ViewBag.karfarma;"></div>
                </div>
            </div>

        </div>
    </div><!-- Top Report End -->
</div><!-- Top Report Wrap End -->

<div class="row mbn-30">

    <!-- Revenue Statistics Chart Start -->
    <div class="col-md-12 mb-30">
        <div class="box">
            <div class="box-head">
                <h4 class="title">آمار درآمد</h4>
            </div>
            <div class="box-body">
                <div class="chartjs-revenue-statistics-chart" id="chartContainer" style="height: 370px; width: 100%;"></div>
            </div>
        </div>
    </div><!-- Revenue Statistics Chart End -->

    <div class="col-12 mb-30">
        <div class="box">
            <div class="box-head">
                <h4 class="title">بسته ها</h4>
            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table table-vertical-middle table-selectable">

                        <!-- Table Head Start -->
                        <thead>
                            <tr>

                                <!--<th class="selector h5"><button class="button-check"></button></th>-->
                                <th><span>نام محصول</span></th>
                                <th><span>قیمت</span></th>
                                <th><span>وضعبت</span></th>

                            </tr>
                        </thead><!-- Table Head End -->
                        <!-- Table Body Start -->
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td><a href="#">@item.BoxName</a></td>
                                    <td>@item.Price</td>
                                    <td><span class="badge badge-success"><a onclick="view(@item.BoxCategoryID)">مشاهده جزِئیات </a></span></td>
                                    <td><a class="h3" href="@Url.Action("EditBox","Box", new { id = item.BoxCategoryID })"><i class="zmdi zmdi-more"></i></a></td>
                                </tr>
                            }
                        </tbody><!-- Table Body End -->

                    </table>
                </div>
            </div>
        </div>
    </div><!-- Recent Transaction End -->
    <!-- Modal -->
    <div class="modal fade" id="MyModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" id="myModalBody">
                    ...
                </div>
            </div>
        </div>
    </div>
</div>
@section PageScript
{
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script>
        function view(id) {
            $.get("/Admin/Box/ShowBox/" + id, function (res) {

                $("#MyModal").modal();
                $("#myModalBody").html(res);

            });
        }
    </script>
    <script>

        window.onload = function () {
         var chart = new CanvasJS.Chart("chartContainer", {
             theme: "dark2",
	    animationEnabled: true,
	    title: {
		text: "نمودار فروش بسته های اگهی"
	},
	toolTip: {
		shared: true
	},
	data: [{
		type: "line",
        name: "طلایی",
		showInLegend: true,
		dataPoints: @Html.Raw(ViewBag.DataPoints1),
	}, {
		type: "line",
		name: "نقره ای",
		showInLegend: true,
		dataPoints: @Html.Raw(ViewBag.DataPoints2),
	}, {
		type: "line",
		name: "برنز",
		showInLegend: true,
		dataPoints: @Html.Raw(ViewBag.DataPoints3),
	}]
});
chart.render();

}

    </script>
}

UscProject/Areas/Admin/Views/Panel/PersonalInformation.cshtml
@model UscProject.Models.UserTB
@{
    ViewBag.Title = "PersonalInformation";
    ViewBag.UserProfile = "active";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
    string path;
    if (Model.ImageName == true)
    {
        path = Url.Content("~/Files/UserPictures/Custom/" + Model.PictureName);
    }
    else
    {
         path = Url.Content("~/Files/UserPictures/Default/UserProfile.jpg");
    }


}
<div class="col-xlg-12 col-12 mb-60 input-group">

    @using (Html.BeginForm("PersonalInformation", "Panel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(m => m.UserID);
        @Html.HiddenFor(m => m.RoleID);
        @Html.HiddenFor(m => m.RegesterDate);
        @Html.HiddenFor(m => m.IsActive);
        @Html.HiddenFor(m => m.ActiveCode);
        @Html.HiddenFor(m => m.ImageName);
        @Html.HiddenFor(m => m.PictureName);
        <div class="row">
            <div class="col-xlg-12 col-lg-6 col-12 mb-30 ">
                <div class="box">
                    <div class="box-head">
                        <h3 class="title">اطلاعات ادمین</h3>
                    </div>
                    <div class="box-body">
                        <div class="form">
                            <div class="row row-10 mbn-20">
                                <div class="col-sm-6 col-12 mb-20"><input type="text" name="UserName" class="form-control" value="@Model.UserName">نام کاربری</div>
                                <div class="col-12 mb-20"><input type="email" name="Email" class="form-control" value="@Model.Email">ایمیل</div>
                                <div class="col-sm-6 col-12 mb-20"><input type="password" name="Password" class="form-control" value="@Model.Password">پسورد</div>

                            </div>

                        </div>
                    </div>

                    <div class="col-12 mt-10 mb-20">
                        <input type="submit" class="button button-primary button-outline" id="form-uploadpic" value="ذخیره تغییرات">
                    </div>
                </div>
            </div>

            <div class="col-xlg-12 col-lg-6 col-12 mb-30">

                <div class="col-12 mb-30">
                    <div class="box">

                        <div class="box-head">
                            <h3 class="title">از بین بردن</h3>
                        </div>

                        <div class="form-group">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="box-body">
                                    <div class="row mbn-20">

                                        <!--Default Uploader Start-->
                                        <div class="col-lg-6 col-12 mb-20">
                                            <h6 class="mb-15">فایل پیش بارگذاری شده</h6>

                                            <input class="dropify" type="file" name="ImgUp" id="ImgUp" data-default-file="@path" />

                                        </div>
                                        <!--Default Uploader End-->
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }
</div>

<!--Dropify End-->
@section PageScript
{
    <script src="~/Areas/Admin/Content/assets/js/plugins/filepond/filepond.min.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/filepond/filepond-plugin-image-exif-orientation.min.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/filepond/filepond-plugin-image-preview.min.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/filepond/filepond.active.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/dropify/dropify.min.js"></script>
    <script src="~/Areas/Admin/Content/assets/js/plugins/dropify/dropify.active.js"></script>
    <script src="~/Areas/Admin/Content/assets/AjaxForm/jquery.form.min.js"></script>


}